import type { CountryProfile, Bloc } from "@/types";
import { promises as fs } from "fs";
import path from "path";

let profilesCache: CountryProfile[] | null = null;
let blocsCache: Bloc[] | null = null;

export async function loadCountryProfiles(): Promise<CountryProfile[]> {
  if (profilesCache) return profilesCache;

  const filePath = path.join(process.cwd(), "data", "country-profiles.json");

  try {
    const raw = await fs.readFile(filePath, "utf-8");
    profilesCache = JSON.parse(raw) as CountryProfile[];
    return profilesCache;
  } catch {
    // Fallback: generate minimal profiles if data file doesn't exist yet
    profilesCache = generateMinimalProfiles();
    return profilesCache;
  }
}

export async function loadBlocs(): Promise<Bloc[]> {
  if (blocsCache) return blocsCache;

  const filePath = path.join(process.cwd(), "data", "blocs.json");

  try {
    const raw = await fs.readFile(filePath, "utf-8");
    blocsCache = JSON.parse(raw) as Bloc[];
    return blocsCache;
  } catch {
    blocsCache = generateMinimalBlocs();
    return blocsCache;
  }
}

function generateMinimalProfiles(): CountryProfile[] {
  // Seed with key countries for demo purposes
  // Full dataset will be generated by scripts/build-country-profiles.ts
  const countries: Partial<CountryProfile>[] = [
    { iso3: "USA", name: "United States", region: "WEOG", scStatus: "P5", idealPoint: -0.85, democracyIndex: 0.78 },
    { iso3: "GBR", name: "United Kingdom", region: "WEOG", scStatus: "P5", idealPoint: -0.65, democracyIndex: 0.87 },
    { iso3: "FRA", name: "France", region: "WEOG", scStatus: "P5", idealPoint: -0.45, democracyIndex: 0.84 },
    { iso3: "RUS", name: "Russia", region: "EEG", scStatus: "P5", idealPoint: 0.70, democracyIndex: 0.21 },
    { iso3: "CHN", name: "China", region: "APG", scStatus: "P5", idealPoint: 0.65, democracyIndex: 0.15 },
    { iso3: "IND", name: "India", region: "APG", scStatus: "none", idealPoint: 0.30, democracyIndex: 0.55 },
    { iso3: "BRA", name: "Brazil", region: "GRULAC", scStatus: "none", idealPoint: 0.15, democracyIndex: 0.65 },
    { iso3: "NGA", name: "Nigeria", region: "AFRICAN", scStatus: "none", idealPoint: 0.25, democracyIndex: 0.42 },
    { iso3: "ZAF", name: "South Africa", region: "AFRICAN", scStatus: "none", idealPoint: 0.20, democracyIndex: 0.62 },
    { iso3: "DEU", name: "Germany", region: "WEOG", scStatus: "none", idealPoint: -0.55, democracyIndex: 0.92 },
    { iso3: "JPN", name: "Japan", region: "APG", scStatus: "none", idealPoint: -0.60, democracyIndex: 0.83 },
    { iso3: "MEX", name: "Mexico", region: "GRULAC", scStatus: "none", idealPoint: 0.10, democracyIndex: 0.58 },
    { iso3: "EGY", name: "Egypt", region: "AFRICAN", scStatus: "none", idealPoint: 0.40, democracyIndex: 0.25 },
    { iso3: "SAU", name: "Saudi Arabia", region: "APG", scStatus: "none", idealPoint: 0.55, democracyIndex: 0.12 },
    { iso3: "AUS", name: "Australia", region: "WEOG", scStatus: "none", idealPoint: -0.60, democracyIndex: 0.89 },
    { iso3: "CAN", name: "Canada", region: "WEOG", scStatus: "none", idealPoint: -0.50, democracyIndex: 0.91 },
    { iso3: "ARG", name: "Argentina", region: "GRULAC", scStatus: "none", idealPoint: 0.05, democracyIndex: 0.70 },
    { iso3: "IDN", name: "Indonesia", region: "APG", scStatus: "none", idealPoint: 0.35, democracyIndex: 0.50 },
    { iso3: "TUR", name: "Turkey", region: "WEOG", scStatus: "none", idealPoint: 0.30, democracyIndex: 0.35 },
    { iso3: "IRN", name: "Iran", region: "APG", scStatus: "none", idealPoint: 0.75, democracyIndex: 0.18 },
    { iso3: "KOR", name: "Republic of Korea", region: "APG", scStatus: "none", idealPoint: -0.45, democracyIndex: 0.82 },
    { iso3: "SWE", name: "Sweden", region: "WEOG", scStatus: "none", idealPoint: -0.40, democracyIndex: 0.95 },
    { iso3: "NOR", name: "Norway", region: "WEOG", scStatus: "none", idealPoint: -0.35, democracyIndex: 0.96 },
    { iso3: "CUB", name: "Cuba", region: "GRULAC", scStatus: "none", idealPoint: 0.80, democracyIndex: 0.16 },
    { iso3: "ISR", name: "Israel", region: "WEOG", scStatus: "none", idealPoint: -0.70, democracyIndex: 0.73 },
    { iso3: "PAK", name: "Pakistan", region: "APG", scStatus: "none", idealPoint: 0.45, democracyIndex: 0.30 },
    { iso3: "KEN", name: "Kenya", region: "AFRICAN", scStatus: "none", idealPoint: 0.20, democracyIndex: 0.48 },
    { iso3: "COL", name: "Colombia", region: "GRULAC", scStatus: "none", idealPoint: -0.10, democracyIndex: 0.62 },
    { iso3: "VNM", name: "Viet Nam", region: "APG", scStatus: "none", idealPoint: 0.60, democracyIndex: 0.20 },
    { iso3: "ETH", name: "Ethiopia", region: "AFRICAN", scStatus: "none", idealPoint: 0.35, democracyIndex: 0.28 },
  ];

  return countries.map((c) => ({
    iso3: c.iso3!,
    name: c.name!,
    region: c.region!,
    blocs: [],
    scStatus: c.scStatus!,
    idealPoint: c.idealPoint!,
    policyDimensions: {
      sovereignty: c.idealPoint! * 0.8 + (Math.random() - 0.5) * 0.3,
      humanRights: -c.idealPoint! * 0.6 + (Math.random() - 0.5) * 0.3,
      development: c.idealPoint! * 0.4 + (Math.random() - 0.5) * 0.3,
      security: (Math.random() - 0.5) * 0.6,
      environment: -c.idealPoint! * 0.5 + (Math.random() - 0.5) * 0.3,
      decolonization: c.idealPoint! * 0.5 + (Math.random() - 0.5) * 0.2,
    },
    votingHistory: {
      totalVotes: 500 + Math.floor(Math.random() * 2000),
      yesRate: 0.5 + c.idealPoint! * 0.2,
      noRate: 0.2 - c.idealPoint! * 0.1,
      abstainRate: 0.3 - c.idealPoint! * 0.1,
      byTopic: {},
    },
    treaties: [],
    gdpPerCapita: 10000 + Math.random() * 50000,
    population: 1000000 + Math.random() * 1400000000,
    governmentType: c.democracyIndex! > 0.7 ? "Democracy" : c.democracyIndex! > 0.4 ? "Hybrid" : "Authoritarian",
    democracyIndex: c.democracyIndex!,
  })) as CountryProfile[];
}

function generateMinimalBlocs(): Bloc[] {
  return [
    {
      id: "g77",
      name: "Group of 77 + China",
      shortName: "G77",
      members: ["CHN", "IND", "BRA", "NGA", "ZAF", "MEX", "EGY", "SAU", "IDN", "IRN", "CUB", "PAK", "KEN", "COL", "VNM", "ETH", "ARG"],
      cohesionScore: 0.6,
      policyLeanings: { sovereignty: 0.6, development: 0.7, decolonization: 0.5 },
      description: "Coalition of developing nations advocating for South-South cooperation",
    },
    {
      id: "weog-like",
      name: "Western European and Others",
      shortName: "WEOG",
      members: ["USA", "GBR", "FRA", "DEU", "JPN", "AUS", "CAN", "KOR", "SWE", "NOR", "ISR"],
      cohesionScore: 0.7,
      policyLeanings: { humanRights: 0.6, environment: 0.4, sovereignty: -0.3 },
      description: "Western democracies with generally aligned voting patterns",
    },
    {
      id: "nam",
      name: "Non-Aligned Movement",
      shortName: "NAM",
      members: ["IND", "ZAF", "EGY", "IDN", "IRN", "CUB", "VNM", "ETH", "NGA", "KEN"],
      cohesionScore: 0.4,
      policyLeanings: { sovereignty: 0.7, decolonization: 0.6 },
      description: "Countries not formally aligned with major power blocs",
    },
  ];
}
