"use client";

import { useState } from "react";
import { COMMITTEES } from "@/engines/committees";
import type { Committee } from "@/types";

interface BriefingResult {
  simulation: { totals: { yes: number; no: number; abstain: number }; passed: boolean; committee: Committee };
  briefing: {
    supporters: { iso3: string; name: string; confidence: number }[];
    opponents: { iso3: string; name: string; confidence: number }[];
    abstainers: { iso3: string; name: string; confidence: number }[];
    keyCountryAnalysis: {
      iso3: string; name: string; predictedVote: string; confidence: number;
      factors: { name: string; score: number; weight: number; description: string }[];
      kgData: { positions: { issueName: string; yesRate: number; noRate: number; sampleSize: number }[]; topAllies: string[]; topRivals: string[]; blocs: string[] };
    }[];
    persuadableCountries: { iso3: string; name: string; currentPrediction: string; confidence: number; swingFactors: string[] }[];
    coalitionStrategy: { strongSupportBlocs: { bloc: string; supporters: number }[]; totalStrongSupport: number; marginOfVictory: number };
  };
  policyVector: Record<string, number>;
}

const COMMITTEE_LIST = Object.values(COMMITTEES);

export default function MunPrepPage() {
  const [policy, setPolicy] = useState("");
  const [committee, setCommittee] = useState<Committee>("GA_PLENARY");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<BriefingResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleAnalyze = async () => {
    if (policy.length < 20) return;
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/simulate/mun-analysis", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ policy, committee }),
      });
      if (!res.ok) throw new Error("Analysis failed");
      setResult(await res.json());
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed");
    } finally {
      setLoading(false);
    }
  };

  const exportMarkdown = () => {
    if (!result) return;
    const b = result.briefing;
    const md = `# MUN Briefing: Resolution Analysis

## Resolution
${policy}

## Committee: ${COMMITTEES[result.simulation.committee]?.name || result.simulation.committee}

## Vote Prediction
- **Yes**: ${result.simulation.totals.yes} | **No**: ${result.simulation.totals.no} | **Abstain**: ${result.simulation.totals.abstain}
- **Outcome**: ${result.simulation.passed ? "PASSES" : "FAILS"}
- **Margin**: ${b.coalitionStrategy.marginOfVictory} votes

## Coalition Strategy
Strong support from ${b.coalitionStrategy.totalStrongSupport} countries.

### Key Supporting Blocs
${b.coalitionStrategy.strongSupportBlocs.map((bl) => `- ${bl.bloc}: ${bl.supporters} confirmed supporters`).join("\n")}

## Top Supporters (target for co-sponsorship)
${b.supporters.slice(0, 10).map((s) => `- **${s.name}** (${(s.confidence * 100).toFixed(0)}% confidence)`).join("\n")}

## Key Opponents
${b.opponents.slice(0, 10).map((o) => `- **${o.name}** (${(o.confidence * 100).toFixed(0)}% confidence)`).join("\n")}

## Persuadable Countries (swing votes)
These countries are near the decision boundary and could be swayed with targeted arguments:

${b.persuadableCountries.map((p) => `- **${p.name}** — currently leaning ${p.currentPrediction} (${(p.confidence * 100).toFixed(0)}% confidence)
  - Swing factors: ${p.swingFactors.join(", ")}`).join("\n")}

## Key Country Analysis
${b.keyCountryAnalysis.map((k) => `### ${k.name} — Predicted: ${k.predictedVote}
- Confidence: ${(k.confidence * 100).toFixed(0)}%
- Allies: ${k.kgData.topAllies.join(", ")}
- Rivals: ${k.kgData.topRivals.join(", ")}
- Blocs: ${k.kgData.blocs.join(", ")}
- Voting record: ${k.kgData.positions.map((p) => `${p.issueName} (${(p.yesRate * 100).toFixed(0)}%Y/${(p.noRate * 100).toFixed(0)}%N, n=${p.sampleSize})`).join("; ")}
- Key factors: ${k.factors.map((f) => `${f.name} (${f.score > 0 ? "+" : ""}${f.score.toFixed(2)})`).join(", ")}
`).join("\n")}

---
*Generated by UNSim Knowledge Graph (unsim.apurvad.xyz)*
*Data: Voeten UNGA Voting Data, Harvard Dataverse | V-Dem v14*
`;
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "mun-briefing.md";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <main className="min-h-screen bg-[var(--color-bg)]">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-white/90 backdrop-blur-md border-b border-[var(--color-border)]">
        <div className="max-w-6xl mx-auto px-6 py-3 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <a href="/" className="text-xs text-[var(--color-muted)] hover:text-[var(--color-ink)]">&larr; Home</a>
            <div className="h-4 w-px bg-[var(--color-border)]" />
            <h1 className="text-sm font-medium">MUN Preparation Tool</h1>
          </div>
          {result && (
            <div className="flex gap-2">
              <button onClick={exportMarkdown} className="text-xs px-3 py-1.5 rounded-lg border border-[var(--color-border)] hover:border-[var(--color-un-blue)] hover:text-[var(--color-un-blue)] transition-colors">
                Export Markdown
              </button>
            </div>
          )}
        </div>
      </header>

      <div className="max-w-6xl mx-auto px-6 py-10">
        {!result ? (
          /* Input form */
          <div className="max-w-2xl mx-auto space-y-8">
            <div className="text-center space-y-3">
              <h2 className="text-3xl font-semibold tracking-tight" style={{ fontFamily: "var(--font-serif)" }}>
                Analyze Your Resolution
              </h2>
              <p className="text-[var(--color-muted)] text-sm max-w-lg mx-auto">
                Describe your resolution idea and get a data-backed briefing: who will support it, who will oppose,
                which countries are persuadable, and what arguments to use — all grounded in 75 years of UNGA voting data.
              </p>
            </div>

            <div className="space-y-5">
              <div>
                <label className="block text-sm font-medium text-[var(--color-ink)] mb-2">Resolution / Policy Idea</label>
                <textarea
                  value={policy}
                  onChange={(e) => setPolicy(e.target.value)}
                  placeholder="Describe your resolution in plain language. Be specific about what it demands, who it targets, and what mechanisms it creates. Example: 'A resolution demanding all nations declare a moratorium on deep-sea mining until environmental impact assessments are completed, with a binding compliance mechanism and penalties for violations...'"
                  className="w-full h-40 px-4 py-3 rounded-xl border border-[var(--color-border)] bg-white text-[var(--color-ink)] placeholder:text-[var(--color-muted)]/50 focus:outline-none focus:ring-2 focus:ring-[var(--color-un-blue)]/30 focus:border-[var(--color-un-blue)] resize-none text-[15px] leading-relaxed"
                />
                <p className="text-xs text-[var(--color-muted)] mt-1.5">{policy.length}/20 min characters · More detail = more accurate analysis</p>
              </div>

              <div>
                <label className="block text-sm font-medium text-[var(--color-ink)] mb-2">UN Committee</label>
                <select
                  value={committee}
                  onChange={(e) => setCommittee(e.target.value as Committee)}
                  className="w-full px-4 py-3 rounded-xl border border-[var(--color-border)] bg-white text-[var(--color-ink)] focus:outline-none focus:ring-2 focus:ring-[var(--color-un-blue)]/30"
                >
                  {COMMITTEE_LIST.map((c) => (
                    <option key={c.id} value={c.id}>{c.name}</option>
                  ))}
                </select>
              </div>

              <button
                onClick={handleAnalyze}
                disabled={policy.length < 20 || loading}
                className="w-full py-3.5 rounded-xl bg-[var(--color-un-blue)] text-white font-medium hover:bg-[var(--color-un-blue-dark)] disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
              >
                {loading ? "Analyzing with Knowledge Graph..." : "Analyze Resolution"}
              </button>

              {error && <p className="text-sm text-[var(--color-vote-no)] text-center">{error}</p>}
            </div>
          </div>
        ) : (
          /* Results */
          <div className="space-y-8">
            {/* Vote summary */}
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-2xl font-semibold" style={{ fontFamily: "var(--font-serif)" }}>Resolution Analysis</h2>
                <p className="text-sm text-[var(--color-muted)] mt-1">{COMMITTEES[result.simulation.committee]?.name}</p>
              </div>
              <div className="text-right">
                <div className={`text-2xl font-bold ${result.simulation.passed ? "text-[var(--color-vote-yes)]" : "text-[var(--color-vote-no)]"}`}>
                  {result.simulation.passed ? "PASSES" : "FAILS"}
                </div>
                <div className="text-sm text-[var(--color-muted)]">
                  {result.simulation.totals.yes}Y · {result.simulation.totals.no}N · {result.simulation.totals.abstain}A
                </div>
              </div>
            </div>

            {/* Vote bar */}
            <div className="h-4 rounded-full overflow-hidden flex bg-[var(--color-bg)]">
              <div className="bg-[var(--color-vote-yes)]" style={{ width: `${(result.simulation.totals.yes / 193) * 100}%` }} />
              <div className="bg-[var(--color-vote-no)]" style={{ width: `${(result.simulation.totals.no / 193) * 100}%` }} />
              <div className="bg-[var(--color-vote-abstain)]" style={{ width: `${(result.simulation.totals.abstain / 193) * 100}%` }} />
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              {/* Coalition strategy */}
              <div className="p-5 rounded-xl border border-[var(--color-border)] bg-white space-y-4">
                <h3 className="text-sm font-semibold">Coalition Strategy</h3>
                <div className="grid grid-cols-2 gap-3">
                  <div className="p-3 rounded-lg bg-[var(--color-vote-yes)]/10">
                    <div className="text-xl font-bold text-[var(--color-vote-yes)]" style={{ fontFamily: "var(--font-mono)" }}>
                      {result.briefing.coalitionStrategy.totalStrongSupport}
                    </div>
                    <div className="text-[10px] text-[var(--color-muted)]">Strong supporters</div>
                  </div>
                  <div className="p-3 rounded-lg bg-[var(--color-un-blue)]/10">
                    <div className="text-xl font-bold text-[var(--color-un-blue)]" style={{ fontFamily: "var(--font-mono)" }}>
                      +{result.briefing.coalitionStrategy.marginOfVictory}
                    </div>
                    <div className="text-[10px] text-[var(--color-muted)]">Vote margin</div>
                  </div>
                </div>
                <div>
                  <h4 className="text-[10px] font-semibold text-[var(--color-muted)] uppercase mb-2">Supporting Blocs</h4>
                  {result.briefing.coalitionStrategy.strongSupportBlocs.map((bl) => (
                    <div key={bl.bloc} className="flex justify-between py-1 text-xs">
                      <span>{bl.bloc}</span>
                      <span className="text-[var(--color-vote-yes)] font-mono">{bl.supporters}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Persuadable countries */}
              <div className="p-5 rounded-xl border border-[var(--color-border)] bg-white space-y-4">
                <h3 className="text-sm font-semibold">Swing Votes (Persuadable)</h3>
                <p className="text-[11px] text-[var(--color-muted)]">These countries are near the decision boundary. Target them with specific arguments.</p>
                <div className="space-y-2">
                  {result.briefing.persuadableCountries.slice(0, 6).map((p) => (
                    <div key={p.iso3} className="p-2 rounded-lg bg-[var(--color-bg)]">
                      <div className="flex items-center justify-between">
                        <span className="text-xs font-medium">{p.name}</span>
                        <span className={`text-[10px] font-mono ${p.currentPrediction === "Yes" ? "text-[var(--color-vote-yes)]" : p.currentPrediction === "No" ? "text-[var(--color-vote-no)]" : "text-[var(--color-vote-abstain)]"}`}>
                          {p.currentPrediction} ({(p.confidence * 100).toFixed(0)}%)
                        </span>
                      </div>
                      {p.swingFactors.length > 0 && (
                        <p className="text-[9px] text-[var(--color-muted)] mt-0.5">Weak on: {p.swingFactors.join(", ")}</p>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              {/* Top supporters for co-sponsorship */}
              <div className="p-5 rounded-xl border border-[var(--color-border)] bg-white space-y-4">
                <h3 className="text-sm font-semibold">Co-Sponsorship Targets</h3>
                <p className="text-[11px] text-[var(--color-muted)]">Most likely to co-sponsor. Approach these first.</p>
                <div className="space-y-1">
                  {result.briefing.supporters.slice(0, 8).map((s) => (
                    <div key={s.iso3} className="flex justify-between py-1 text-xs">
                      <span>{s.name}</span>
                      <span className="text-[var(--color-vote-yes)] font-mono">{(s.confidence * 100).toFixed(0)}%</span>
                    </div>
                  ))}
                </div>
                <div className="pt-3 border-t border-[var(--color-border)]">
                  <h4 className="text-[10px] font-semibold text-[var(--color-vote-no)] uppercase mb-2">Key Opponents</h4>
                  {result.briefing.opponents.slice(0, 5).map((o) => (
                    <div key={o.iso3} className="flex justify-between py-1 text-xs">
                      <span>{o.name}</span>
                      <span className="text-[var(--color-vote-no)] font-mono">{(o.confidence * 100).toFixed(0)}%</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Detailed country analysis */}
            <div className="space-y-4">
              <h3 className="text-lg font-semibold" style={{ fontFamily: "var(--font-serif)" }}>Country-Level Intelligence</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {result.briefing.keyCountryAnalysis.map((k) => (
                  <div key={k.iso3} className="p-4 rounded-xl border border-[var(--color-border)] bg-white space-y-3">
                    <div className="flex items-center justify-between">
                      <h4 className="font-medium">{k.name}</h4>
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${
                        k.predictedVote === "Yes" ? "bg-[var(--color-vote-yes)]/10 text-[var(--color-vote-yes)]" :
                        k.predictedVote === "No" ? "bg-[var(--color-vote-no)]/10 text-[var(--color-vote-no)]" :
                        "bg-[var(--color-vote-abstain)]/10 text-[var(--color-vote-abstain)]"
                      }`}>
                        {k.predictedVote} ({(k.confidence * 100).toFixed(0)}%)
                      </span>
                    </div>
                    <div className="text-[11px] text-[var(--color-muted)] space-y-1">
                      <p><strong>Allies:</strong> {k.kgData.topAllies.join(", ") || "—"}</p>
                      <p><strong>Blocs:</strong> {k.kgData.blocs.join(", ") || "—"}</p>
                    </div>
                    <div className="space-y-1">
                      {k.kgData.positions.slice(0, 3).map((pos) => (
                        <div key={pos.issueName} className="flex items-center gap-2 text-[10px]">
                          <span className="text-[var(--color-muted)] w-32 truncate">{pos.issueName}</span>
                          <div className="flex-1 h-1.5 rounded-full overflow-hidden bg-[var(--color-bg)] flex">
                            <div className="bg-[var(--color-vote-yes)]" style={{ width: `${pos.yesRate * 100}%` }} />
                            <div className="bg-[var(--color-vote-no)]" style={{ width: `${pos.noRate * 100}%` }} />
                          </div>
                          <span className="text-[var(--color-muted)] font-mono w-8">n={pos.sampleSize}</span>
                        </div>
                      ))}
                    </div>
                    <div className="text-[10px] text-[var(--color-muted)]">
                      <strong>Key factors:</strong> {k.factors.slice(0, 3).map((f) => `${f.name} (${f.score > 0 ? "+" : ""}${f.score.toFixed(2)})`).join(", ")}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Reset button */}
            <div className="text-center pt-4">
              <button onClick={() => setResult(null)} className="text-sm text-[var(--color-un-blue)] hover:underline">
                ← Analyze another resolution
              </button>
            </div>
          </div>
        )}
      </div>
    </main>
  );
}
